### ISSUE TITLE
what's missing in  `nim r`? maybe recommend as an alternative for nim >= 1.4 in the readme?

### ISSUE THREAD

**Issue by timotheecour** [PMunch/nimcr#14]
```nim
#!/usr/bin/env nim r --hints:off
static: echo "recompiling..." # only appears if recompiling needed
for i in 0..<10:
  echo i
```

```
chmod u+x main.nim
./main.nim # prints recompiling...
./main.nim # does not print recompiling...
# edit main.nim or its dependencies
./main.nim # prints recompiling...
```

## note
-S may be needed on some sysmtems, see https://en.wikipedia.org/wiki/Shebang_(Unix)

eg: `#!/usr/bin/env -S nim r --hints:off`

**Comment by PMunch** [comment]
The main difference I can see is that `nimcr` will compile a release build for speed, and it will hide all compilation output unless it fails to compile. This means that the program is free to write to both stdout and stderr without being "polluted" by the Nim compiler.

**Comment by shirleyquirk** [comment]
@timothee it's a small thing but defaulting to `--hints:off` is whats missing to make it possible to recommend `#!nim r` as a replacement for python or bash to my clients.

**Comment by timotheecour** [comment]
> it's a small thing but defaulting to --hints:off is whats missing
> The main difference I can see is that nimcr will compile a release build for speed,

these are covered by:
```
#!/usr/bin/env nim r --hints:off -d:danger
```

(which also gives you more control, eg you can use `--passc:-flto` or `-d:release`, etc)

> will hide all compilation output unless it fails to compile.

this is covered by: `--hints:off --warnings:off`
unless your code has `static: echo "foo"`, but it's questionable whether you'd want to silence that.

**Comment by PMunch** [comment]
Well, that hides hints and warnings, even if it fails to compile. And of course you'd want to hide static echos, the whole point of this is to give you the exact some output whenever you run the script so that you can easily pipe it to another program for example. With `nim r` you end up with a script that can behave differently depending on whether it has to recompile or not, and if it fails to compile will hide parts of the compiler output. Nimcr on the other hand will keep your full compilation output and show it all to you if the program fails to compile, and if it compiles just fine it will look exactly the same as if it didn't have to recompile.

**Comment by timotheecour** [comment]
> Nimcr on the other hand will keep your full compilation output and show it all to you if the program fails to compile

ok, a separate binary like nimcr is indeed needed for this use case

**Comment by shirleyquirk** [comment]
Yes, it's problematic to elide the compilation and pretend that a nim file is something it's not, despite Nims speed, and much as I'd like to.
